# Generated by Django 5.0.6 on 2024-06-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_position_remove_customer_user_status_customer_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='position',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(null=True, upload_to='customers/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.AddField(
            model_name='customer',
            name='position',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin'), ('SuperAdmin', 'Superadmin'), ('Worker', 'Worker')], default='User', max_length=20),
        ),
    ]
