# Generated by Django 5.0.6 on 2024-06-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_position_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.PositiveIntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='position',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin'), ('SuperAdmin', 'Superadmin'), ('Worker', 'Worker')], default='User', max_length=50),
        ),
    ]
