# Generated by Django 5.0.6 on 2024-06-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='position',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin'), ('Worker', 'Worker')], default='User', max_length=50),
        ),
    ]
