# Generated by Django 5.0.6 on 2024-06-17 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_product_image_blog_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='product_type',
        ),
    ]
